### PR TITLE
chore(box): migrate to @emotion, fix border radius

### PR DESCRIPTION
**Pull request by TrygveUrdahl**
# PR Checklist
https://elvia.atlassian.net/wiki/spaces/TEAMATOM/pages/10427498683/Review+prosess

- [ ] Bumpet package?
- [ ] Updated changelog?
- [ ] Correct date in changelog?

### CODE REVIEW

**Comment by TomSchrier** [comment]
Can we keep the original element name/class in the generated class name?
Styled components included the element name in their classes, but with emotion they just become random strings:
Skjermbilde 2024-05-23 kl  08 15 06
Skjermbilde 2024-05-23 kl  08 14 57

**Comment by TrygveUrdahl** [comment]
> Can we keep the original element name/class in the generated class name? Styled components included the element name in their classes, but with emotion they just become random strings: Skjermbilde 2024-05-23 kl 08 15 06 Skjermbilde 2024-05-23 kl 08 14 57

It should be possible, but it requires the use of the [Emotion Babel plugin](https://emotion.sh/docs/@emotion/babel-plugin), which we do not currently have set up in our build system.

**Comment by TomSchrier** [comment]
Also; unrelated to this PR, why is the Heading area not rendered dynamically? We get some padding on the top of the box, even when there is no heading to render:
`<BoxHeading ref={boxHeading}>{heading}</BoxHeading>`
Skjermbilde 2024-05-23 kl  08 18 35 (2)

**Review by TomSchrier — APPROVED** [review]

**Comment by TrygveUrdahl** [comment]
> Also; unrelated to this PR, why is the Heading area not rendered dynamically? We get some padding on the top of the box, even when there is no heading to render: `<BoxHeading ref={boxHeading}>{heading}</BoxHeading>` Skjermbilde 2024-05-23 kl 08 18 35 (2)

Fair question! Ideally it should not have that, but it would be breaking to change, so I'll just leave it 🥴

**Pull request merged**
